version: '3.8'

services:
  tescom-agent:
    build: .
    ports:
      - "8080:7860"  # Map host port 8080 to container port 7860
    environment:
      # Required API keys (set these in .env file or environment)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      
      # Optional configuration overrides
      - LOG_DIR=/app/logs
      - DB_PATH=/app/data/equipment.db
      - BACKUPS_DIR=/app/backups
      - GRADIO_HOST=0.0.0.0
      - GRADIO_PORT=7860
      
      # Optional logo configuration
      - TESCOM_LOGO_URL=${TESCOM_LOGO_URL:-}
      - TESCOM_LOGO_PATH=/app/assets/tescom-logo.png
    
    volumes:
      # Persist data across container restarts
      - tescom-data:/app/data
      - tescom-logs:/app/logs
      - tescom-backups:/app/backups
      
      # Optional: Mount local assets directory for custom logos
      # - ./assets:/app/assets:ro
    
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Named volumes for data persistence
volumes:
  tescom-data:
    driver: local
  tescom-logs:
    driver: local
  tescom-backups:
    driver: local
